export const menuItemsData = [
  {
    id: 1,
    name: 'Pan-fried camembert',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: '/images/fromage2.png',
  },
  {
    id: 2,
    name: 'Summer Asian Slaw',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: '/images/fromage2.png',
  },
  {
    id: 3,
    name: 'Burger',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: '/images/fromage3.png',
  },
  {
    id: 4,
    name: 'white sauce pasta',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: '/images/fromage2.png',
  },
  {
    id: 5,
    name: 'butterfly pasta',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: '/images/fromage2.png',
  },
  {
    id: 6,
    name: 'tooty fruity bowl',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: '/images/fromage3.png',
  },
  {
    id: 7,
    name: 'granola cereal bowl',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: '/images/fromage2.png',
  },
  {
    id: 8,
    name: 'palm bowl',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: '/images/fromage2.png',
  },
  {
    id: 9,
    name: 'tigela smoothie',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: '/images/fromage3.png',
  },
  {
    id: 10,
    name: 'tigela smoothie',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: '/images/fromage2.png',
  }
]
